### ISSUE TITLE
[check_fortigate.pl]: unkown mem-sys

### ISSUE THREAD

**Issue by sgruber94** [riskersen/Monitoring#75]
Hi,
sorry for the delay.
i have try the new script but i have a mistake 

./check_fortigate.pl -H A.B.C.D -C [COMUNITY] -p [FORTISERIAL_PATH] -T mem-sys
UNKNOWN: OID .1.3.6.1.4.1.12356.101.4.1.4.0.1 does not exist

The script add the .1 for the master and .2 for the slave, but this OID doesn't exist

_Originally posted by @VincentROLLAND in https://github.com/riskersen/Monitoring/issues/59#issuecomment-943207835_

**Comment by VincentROLLAND** [comment]
Hi,

Sorry i was out of office, i have try the scrypt with 0e9b802, but it add again the .1 for master and .2 for slave:

./check_fortigate.pl -H A.B.C.D -C [COMMUNITY] -p [FORTISERIAL_PATH] -T cpu-sys
UNKNOWN: OID .1.3.6.1.4.1.12356.101.4.1.3.0.1 does not exist

./check_fortigate.pl -H A.B.C.D -C [COMMUNITY] -p [FORTISERIAL_PATH]  -T mem-sys
UNKNOWN: OID .1.3.6.1.4.1.12356.101.4.1.4.0.1 does not exist

./check_fortigate.pl -H A.B.C.D -C [COMMUNITY] -p [FORTISERIAL_PATH] -T cpu-sys -s
UNKNOWN: OID .1.3.6.1.4.1.12356.101.4.1.3.0.2 does not exist

./check_fortigate.pl -H A.B.C.D -C [COMMUNITY] -p [FORTISERIAL_PATH] -T mem-sys -s
UNKNOWN: OID .1.3.6.1.4.1.12356.101.4.1.4.0.2 does not exist

**Comment by VincentROLLAND** [comment]
in fact i have try the same script than 1.8.10 with this link https://github.com/riskersen/Monitoring/blob/0e9b80225e0ee95a45bc53f3fc86c1f01a76475a/fortigate/check_fortigate.pl#L553-L564
i'm not used to with github...
Could you provide me the link?

**Comment by sgruber94** [comment]
Hi Vincent,
thats the link: https://github.com/sgruber94/Monitoring-riskersen/blob/check_fortigate_unkownmem/fortigate/check_fortigate.pl

**Comment by VincentROLLAND** [comment]
Hi,
it's OK and reflect the memory form fortigate GUI:
./check_fortigate.pl.1 -H A.B.C.D -C [COMMUNITY] -p [FORTISERIAL_PATH] -T mem-sys
OK: A.B.C.D (Current device: [FORTISERIAL]) Memory is okay: 60%|'memory'=60%;80;90

**Comment by tectumopticum** [comment]
Hi Stefan,
I have a Fortigate 60F in standalone-mode (non-clustered). In the subroutine get_health_value a ".1" is added to the memory-OID ".1.3.6.1.4.1.12356.101.4.1.4.0" because of the $curr_serial-pattern "/^FG/". It matches for this model because $curr_serial begins with "FGT60". But the OID ".1.3.6.1.4.1.12356.101.4.1.4.0.1" is not implemented on this model (tested with snmpwalk). IMHO it is always difficult to derive OIDs hardcoded from the name of a device. I don't know if the OID is implemented for a FGT60 in a cluster.
As a local workaround I changed the pattern of the this line:
`} elsif ( $curr_serial =~ /^(FG100A|FG201|FGT)/ )`
Does anyone has a better idea?
Regards, Henning
